name = "easytier-wsrelay"
main = "build/index.js"
compatibility_date = "2026-05-01"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[durable_objects]
bindings = [
    { name = "RELAY_ROOM", class_name = "RelayRoom" },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelayRoom"]

[observability]
[observability.logs]
enabled = true
invocation_logs = true